name: Release CI

on:
  release:
    types: [released]

jobs:
  build:
    name: Release CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git checkout ${{ github.event.release.target_commitish }}
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
      - name: Maven Build
        run: mvn clean install -DskipTests=true -Ddockerfile.skip=true -B -V
        env:
          GITHUB_TOKEN: ${{ secrets.ORGANIZATION_TOKEN }}
      - name: Maven Verify
        run: mvn verify -B
      - name: Configure git
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
      - name: Prepare release
        id: prepare_release
        run: |
          mvn -B build-helper:parse-version release:prepare \
            -DreleaseVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion} \
            -Darguments="-DskipTests=true -Ddockerfile.skip=true"
          echo ::set-output name=release_tag::$(git describe --tags --abbrev=0)
      - name: Perform release
        run: mvn -B release:perform -Pdeploy2Github -Darguments="-DskipTests=true -Ddockerfile.skip=true -Pdeploy2Github"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Deploy release version to the Maven Central Repository
        run: |
          release_version=$(echo ${{ steps.prepare_release.outputs.release_tag }} | sed "s/release-//")
          echo release version $release_version
          mvn versions:set -DnewVersion=$release_version -DgenerateBackupPoms=false
          mvn versions:commit
          mvn deploy -Pdeploy2Maven -DskipTests -B -V
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Rollback release
        if: failure()
        run: |
          mvn release:rollback || echo "nothing to rollback"
          git push origin :refs/tags/${{ github.event.release.tag_name }}
          if [ ! -z "${{ steps.prepare_release.outputs.release_tag }}" ]
          then
            git tag -d ${{ steps.prepare_release.outputs.release_tag }}
            git push origin :refs/tags/${{ steps.prepare_release.outputs.release_tag }}
          fi
